name: deploy-blogs

on:
  push:
    branches: [ "blog", "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/zxunge.github.io

    - name: deploy
      run: |
        mkdir ~/blogs

        git config --local user.email "3396563372@qq.com"
        git config --local user.name "zxunge"
        git fetch origin blog:blog
        git checkout blog

        COMMIT_INFO=$(git log -n 1 | tail -n 1)

        cp -rf * ~/blogs/
        git checkout main
        mkdir -p blogs
        rm -rf ./blogs/*
        cp -rf ~/blogs/* ./blogs/
        git add blogs/*
        git commit -am "${COMMIT_INFO}"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: main

